---
- name: Load var file with package names based on the OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install FreeIPA client
  block:
    - name: Install FreeIPA client (Debian Bullseye)
      ansible.builtin.package:
        name: "{{ package_names }}"
        default_release: "{{ ansible_distribution_release }}-backports"
      when:
        - ansible_distribution == "Debian"
        - ansible_distribution_release == "bullseye"

    - name: Install FreeIPA client (not Debian Bullseye)
      ansible.builtin.package:
        name: "{{ package_names }}"
      when:
        - not (ansible_distribution == "Debian" and ansible_distribution_release == "bullseye")

- name: Copy setup script
  ansible.builtin.copy:
    src: 00_setup_freeipa.sh
    owner: root
    mode: 0500
    dest: /usr/local/sbin/
