---
- name: Load var file with package names based on the OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install FreeIPA client
  block:
    - name: Install FreeIPA client
      ansible.builtin.package:
        name: "{{ package_names }}"
    # On Debian Bullseye and later, the default /etc/krb5.conf file
    # uses a FILE value for this option.  The /etc/krb5.conf file is
    # then overwritten when the 00_setup_freeipa.sh script is run, and
    # the new file uses the KEYRING value specified below.  This
    # causes a problem since before running that script we kinit,
    # which stores our keytab in a file that is then ignored by
    # Kerberos due to the new configuration.  To avoid this wrinkle we
    # simply adjust the default configuration to use the preferred
    # value before the script can ever be run.
    - name: Set default ccache name for Kerberos (Debian Bullseye and later)
      community.general.ini_file:
        # These are the permissions that are set by default on
        # Debian Bullseye and later.
        mode: 0644
        option: default_ccache_name
        path: /etc/krb5.conf
        section: libdefaults
        value: KEYRING:persistent:%{uid}
      when:
        - ansible_distribution == "Debian"
        - ansible_distribution_release != "buster"

- name: Copy setup script
  ansible.builtin.copy:
    src: 00_setup_freeipa.sh
    owner: root
    mode: 0500
    dest: /usr/local/sbin/
