---
- name: Install FreeIPA client
  package:
    name: freeipa-client
    state: present

- name: Install enrollment helper script
  copy:
    src: setup_freeipa.sh
    owner: root
    mode: 0700
    dest: /usr/local/sbin/

- name: Install FreeIPA enrollment service
  copy:
    src: freeipa-enroll.service
    owner: root
    mode: 0644
    dest: /lib/systemd/system/

- debug:
    msg: ansible_service_mgr == {{ ansible_service_mgr }}

# Unless you do this, systemd can sometimes get confused when you try
# to start a service you just installed
- name: Systemd daemon-reload
  systemd:
    daemon_reload: true
  when:
    - ansible_service_mgr == "systemd"

- name: Enable FreeIPA enrollment service
  service:
    name: freeipa-enroll
    enabled: yes
    state: stopped
