---
- name: Load var file with package names based on the OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        # Add regex_replace() filters to remove spaces and
        # slashes. This allows the OS family/distribution for Kali,
        # "Kali GNU/Linux", to be easily mapped to a vars file.
        - "{{ ansible_distribution | regex_replace('[ /]', '_') }}_{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution | regex_replace('[ /]', '_') }}.yml"
        - "{{ ansible_os_family | regex_replace('[ /]', '_') }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install FreeIPA client
  package:
    name: "{{ package_names }}"

- name: Install enrollment helper script
  copy:
    src: setup_freeipa.sh
    owner: root
    mode: 0500
    dest: /usr/local/sbin/

- name: Install FreeIPA enrollment service
  copy:
    src: freeipa-enroll.service
    owner: root
    mode: 0644
    dest: /lib/systemd/system/

# Unless you do this, systemd can sometimes get confused when you try
# to start a service you just installed
- name: Systemd daemon-reload
  systemd:
    daemon_reload: true
  when:
    - ansible_service_mgr == "systemd"

- name: Enable FreeIPA enrollment service
  service:
    name: freeipa-enroll
    enabled: yes
    state: stopped
