---
- name: Load var file with package names based on the OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install FreeIPA client
  ansible.builtin.package:
    name: "{{ package_names }}"

- name: Copy setup script
  ansible.builtin.copy:
    src: 00_setup_freeipa.sh
    owner: root
    mode: 0500
    dest: /usr/local/sbin/
